### PR TITLE
Attempt to fix file not found exception when running against project using "java-test-fixtures"

### PR DESCRIPTION
**Pull request by michaelruocco**
Attempt to fix issue #314

### CODE REVIEW

**Comment by michaelruocco** [comment]
Hi @DanielThomas, I noticed there are been a couple of commits to master this week, so I have resolved the conflicts on this PR. Is there any chance that this change can be merged? Or if not is there anything further I need to do to get it into a state that could be merged please?

**Comment by DanielThomas** [comment]
@michaelruocco I'll probably go with a slightly different fix, but this gives me a great head start. Let me merge this and take a look.

**Comment by DanielThomas** [comment]
Not sure how this didn't fail on the main classes directory artifact too, but I'm filtering by `type == 'jar'` now which will make this more reliable.

**Comment by DanielThomas** [comment]
I'm rolling v16.15.9. Should be out within the hour.

**Comment by michaelruocco** [comment]
Ah yeah thats a much better solution, not sure why I didn't think of that! Thanks very much, much appreciated.

**Comment by DanielThomas** [comment]
You're most welcome @michaelruocco! Writing a failing test for a bug is usually the hard part, thanks for doing that.

**Pull request merged**
