### PR TITLE
Add unit-test for nested module-info classes

### PR DESCRIPTION
**Pull request by larsgrefer**
Add unit-test for module-info classes in `META-INF/versions/9/`

### CODE REVIEW

**Comment by rpalcolea** [comment]
Hi @larsgrefer , thanks for the contribution. Added a comment on your test, let me know what you think

**Comment by larsgrefer** [comment]
Hi @rpalcolea

Where did you add a comment? I can't see one.

I opened this PR because gradleLint fails in joinfaces/joinfaces#627 on a duplicate `META-INF/versions/9/module-info.class`.

**Comment by larsgrefer** [comment]
I'm confused that the test I added here succeeds while joinfaces/joinfaces#627 fails:

```
net.bytebuddy:byte-buddy:1.9.5 in configuration ':joinfaces-security-taglib:testCompile' has 1 classes duplicated by net.bytebuddy:byte-buddy-agent:1.9.5. Duplicate classes: [META-INF/versions/9/module-info]
net.bytebuddy:byte-buddy:1.9.5 in configuration ':joinfaces-security-taglib:testCompile' has 1 classes duplicated by org.apache.logging.log4j:log4j-api:2.11.1. Duplicate classes: [META-INF/versions/9/module-info]
Excluding []
Excluding []
net.bytebuddy:byte-buddy:1.9.5 in configuration ':joinfaces-security-taglib:testRuntime' has 1 classes duplicated by net.bytebuddy:byte-buddy-agent:1.9.5. Duplicate classes: [META-INF/versions/9/module-info]
net.bytebuddy:byte-buddy:1.9.5 in configuration ':joinfaces-security-taglib:testRuntime' has 1 classes duplicated by org.apache.logging.log4j:log4j-api:2.11.1. Duplicate classes: [META-INF/versions/9/module-info]
net.bytebuddy:byte-buddy:1.9.5 in configuration ':joinfaces-test:compile' has 1 classes duplicated by net.bytebuddy:byte-buddy-agent:1.9.5. Duplicate classes: [META-INF/versions/9/module-info]
net.bytebuddy:byte-buddy:1.9.5 in configuration ':joinfaces-test:compile' has 1 classes duplicated by org.apache.logging.log4j:log4j-api:2.11.1. Duplicate classes: [META-INF/versions/9/module-info]
net.bytebuddy:byte-buddy:1.9.5 in configuration ':joinfaces-test:testRuntime' has 1 classes duplicated by net.bytebuddy:byte-buddy-agent:1.9.5. Duplicate classes: [META-INF/versions/9/module-info]
net.bytebuddy:byte-buddy:1.9.5 in configuration ':joinfaces-test:testRuntime' has 1 classes duplicated by org.apache.logging.log4j:log4j-api:2.11.1. Duplicate classes: [META-INF/versions/9/module-info]
io.github.classgraph:classgraph:4.6.13 in configuration ':joinfaces-starters:adminfaces-spring-boot-starter:compile' has 1 classes duplicated by org.apache.logging.log4j:log4j-api:2.11.1. Duplicate classes: [META-INF/versions/9/module-info]
io.github.classgraph:classgraph:4.6.13 in configuration ':joinfaces-starters:angularfaces-spring-boot-starter:compile' has 1 classes duplicated by org.apache.logging.log4j:log4j-api:2.11.1. Duplicate classes: [META-INF/versions/9/module-info]
io.github.classgraph:classgraph:4.6.13 in configuration ':joinfaces-starters:bootsfaces-spring-boot-starter:compile' has 1 classes duplicated by org.apache.logging.log4j:log4j-api:2.11.1. Duplicate classes: [META-INF/versions/9/module-info]
io.github.classgraph:classgraph:4.6.13 in configuration ':joinfaces-starters:butterfaces-spring-boot-starter:compile' has 1 classes duplicated by org.apache.logging.log4j:log4j-api:2.11.1. Duplicate classes: [META-INF/versions/9/module-info]
io.github.classgraph:classgraph:4.6.13 in configuration ':joinfaces-starters:icefaces-spring-boot-starter:compile' has 1 classes duplicated by org.apache.logging.log4j:log4j-api:2.11.1. Duplicate classes: [META-INF/versions/9/module-info]
io.github.classgraph:classgraph:4.6.13 in configuration ':joinfaces-starters:jsf-spring-boot-starter:compile' has 1 classes duplicated by org.apache.logging.log4j:log4j-api:2.11.1. Duplicate classes: [META-INF/versions/9/module-info]
Excluding []
Excluding []
Excluding []
io.github.classgraph:classgraph:4.6.13 in configuration ':joinfaces-starters:omnifaces1-spring-boot-starter:compile' has 1 classes duplicated by org.apache.logging.log4j:log4j-api:2.11.1. Duplicate classes: [META-INF/versions/9/module-info]
io.github.classgraph:classgraph:4.6.13 in configuration ':joinfaces-starters:omnifaces3-spring-boot-starter:compile' has 1 classes duplicated by org.apache.logging.log4j:log4j-api:2.11.1. Duplicate classes: [META-INF/versions/9/module-info]
io.github.classgraph:classgraph:4.6.13 in configuration ':joinfaces-starters:primefaces-spring-boot-starter:compile' has 1 classes duplicated by org.apache.logging.log4j:log4j-api:2.11.1. Duplicate classes: [META-INF/versions/9/module-info]
io.github.classgraph:classgraph:4.6.13 in configuration ':joinfaces-starters:primefaces-spring-boot-starter:runtime' has 1 classes duplicated by org.apache.logging.log4j:log4j-api:2.11.1. Duplicate classes: [META-INF/versions/9/module-info]
io.github.classgraph:classgraph:4.6.13 in configuration ':joinfaces-starters:richfaces-spring-boot-starter:compile' has 1 classes duplicated by org.apache.logging.log4j:log4j-api:2.11.1. Duplicate classes: [META-INF/versions/9/module-info]
io.github.classgraph:classgraph:4.6.13 in configuration ':joinfaces-starters:security-spring-boot-starter:compile' has 1 classes duplicated by org.apache.logging.log4j:log4j-api:2.11.1. Duplicate classes: [META-INF/versions/9/module-info]
io.github.classgraph:classgraph:4.6.13 in configuration ':joinfaces-starters:security-spring-boot-starter:runtime' has 1 classes duplicated by org.apache.logging.log4j:log4j-api:2.11.1. Duplicate classes: [META-INF/versions/9/module-info]
```

**Comment by larsgrefer** [comment]
@rpalcolea Now this PR reproduces my problem

**Pull request closed without merging**
