### PR TITLE
Jc/indent by 4

### PR DESCRIPTION
**Pull request by jmcampanini**
when adding into a closure, it should be indented 4 spaces

### CODE REVIEW

**Comment by jmcampanini** [comment]
// @gracew

**Comment by jkschneider** [comment]
Thanks again @jmcampanini!

**Comment by jmcampanini** [comment]
@jkschneider yay ty! any idea on when a new release will be cut? :)

**Comment by jkschneider** [comment]
This and #131 rolled out just a minute ago with version 7.9.4.

**Comment by jmcampanini** [comment]
thank you! :)

**Pull request merged**
